//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCR.PracticaMinions4.LIL.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCR.PracticaMinions4.LIL.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calificación agregada con éxito.
        /// </summary>
        public static string msjCalificacionAgregada {
            get {
                return ResourceManager.GetString("msjCalificacionAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe de elegir una calificación.
        /// </summary>
        public static string msjCalificacionNoSeleccionada {
            get {
                return ResourceManager.GetString("msjCalificacionNoSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino agregado con éxito.
        /// </summary>
        public static string msjDestinoAgregado {
            get {
                return ResourceManager.GetString("msjDestinoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino modificado con éxito.
        /// </summary>
        public static string msjDestinoModificado {
            get {
                return ResourceManager.GetString("msjDestinoModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos deben de estar llenos.
        /// </summary>
        public static string msjErrorCamposVacios {
            get {
                return ResourceManager.GetString("msjErrorCamposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al ejecutar el procedimiento.
        /// </summary>
        public static string msjErrorEjecutarProcedimiento {
            get {
                return ResourceManager.GetString("msjErrorEjecutarProcedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación agregada con éxito.
        /// </summary>
        public static string msjEvaluacionAgregada {
            get {
                return ResourceManager.GetString("msjEvaluacionAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe de elegir una evaluación.
        /// </summary>
        public static string msjEvaluacionNoSeleccionada {
            get {
                return ResourceManager.GetString("msjEvaluacionNoSeleccionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva agregada con éxito.
        /// </summary>
        public static string msjReservaAgregada {
            get {
                return ResourceManager.GetString("msjReservaAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva cancelada con éxito.
        /// </summary>
        public static string msjReservaEliminada {
            get {
                return ResourceManager.GetString("msjReservaEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vuelo agregado con éxito.
        /// </summary>
        public static string msjVueloAgregado {
            get {
                return ResourceManager.GetString("msjVueloAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vuelo modificado con éxito.
        /// </summary>
        public static string msjVueloModificado {
            get {
                return ResourceManager.GetString("msjVueloModificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe de elegir un vuelo.
        /// </summary>
        public static string msjVueloNoSeleccionado {
            get {
                return ResourceManager.GetString("msjVueloNoSeleccionado", resourceCulture);
            }
        }
    }
}
